import './globals.css';
import { DM_Sans, Inter } from 'next/font/google';

const dm_sans = DM_Sans({
  weight: ['400', '500', '700'],
  display: 'swap',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Vman',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>{children}</body>
    </html>
  );
}
